PetGroomingApplication/Controllers/GroomerController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PetGroomingApplication.GenericRepository;
using PetGroomingApplication.Models;
using PetGroomingApplication.Repository;
using PetGroomingApplication.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PetGroomingApplication.Controllers
{
    public class GroomerController : Controller
    {
        private GroomerRepository repository = null;
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
 
        public GroomerController()
        {
            this.repository = new GroomerRepository();
        }

        public GroomerController(GroomerRepository repository)
        {
            this.repository = repository;
        }

        // GET: Groomer/Calendar?date=date
        [Authorize(Roles = "staff")]
        public ActionResult Calendar(DateTime date)
        {
            string userId = User.Identity.GetUserId();
            Groomer groomer = repository.GetByUserId(userId);
            if (groomer == null)
            {
                return Content("Nu a fost gasit contul de stilist pentru userul " + userId.ToString() + "!");
            }
            GroomerCalendarService groomerService = new GroomerCalendarService(groomer);
            List<GroomerCalendarViewModel> calendarView = CalendarViewMapperService.CalendarToGroomerView(groomerService.GetCalendar(date));
           
            ViewBag.Date = date.ToString("dd.MM.yyyy");
            ViewBag.groomerName = groomer.Name;
            return View("Appointments", calendarView);
        }

        // GET: Groomer
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var groomers = repository.GetAll();
            return View("Index", groomers);
        }

        // GET: Groomer/Details/5
        public ActionResult Details(Guid id)
        {
            return View();
        }

        // GET: Groomer/Register
        [Authorize(Roles = "admin")]
        public ActionResult Register()
        {
            GroomerRegisterViewModel groomer = new  GroomerRegisterViewModel();
            return View("Register", groomer);
        }

        // POST: Groomer/Register - with user
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]

        public async Task<ActionResult> Register(GroomerRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Name,
                    Email = model.Email
                };
                model.Password = RandomPasswordService.GenerateRandomPassword(); // random password
                var result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, "staff");
                    //await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    //create groomer
                    Groomer groomer = new Groomer();
                    UpdateModel(groomer);
                    groomer.UserId = user.Id;
                    repository.Insert(groomer);
                    repository.Save();

                    // send email to groomer with user & password
                    string subject = "Pet Grooming credentials";
                    ViewBag.UserName = model.Name;
                    ViewBag.Password = model.Password;
                    string message = RenderRazorViewToString("RegisterEmail", null);
                    string emailResult;
                    try
                    {
                        PetGroomingApplication.Services.Email.Send(model.Email, subject, message);
                        emailResult = "The message was sent sussessfully";
                    }
                    catch (Exception ex)
                    {
                        emailResult = ex.Message;
                    }
                    //      log on disk
                    string fileName = Path.GetFullPath(Server.MapPath(@"~/Data/Sent_credentials.txt"));
                    using (StreamWriter file = new StreamWriter(fileName, true))
                    {
                        file.WriteLine($"{DateTime.Now}\nUser name: {model.Name} \nPassword: {model.Password}\n-------------------");
                    }

                    ViewBag.EmailResult = emailResult;
                    return RedirectToAction("SuccessRegister");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //GET: Groomer/Success register
        public ActionResult SuccessRegister(string email, string pass)
        {
            
               return View("SuccessRegister");
        }


        // GET: Groomer/Edit/5
        [Authorize(Roles = "staff, admin")]
        public ActionResult Edit(Guid id)
        {
            Groomer groomer = repository.GetById(id);
            return View("Edit", groomer);
        }

        // POST: Groomer/Edit/5
        [HttpPost]
        [Authorize(Roles = "staff, admin")]
        public ActionResult Edit(Guid id, FormCollection collection)
        {
            Groomer groomer = new Groomer();
            try
            {
                UpdateModel(groomer);
                repository.Update(groomer);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit", groomer);
            }
        }

        // GET: Groomer/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(Guid id)
        {
            Groomer groomer = repository.GetById(id);
            return View("Delete", groomer);
        }

         // POST: Groomer/Delete/5
        [HttpPost]
        [Authorize(Roles ="admin")]
        public async Task<ActionResult> Delete(Guid id, FormCollection collection)
        {
            Groomer groomer = repository.GetById(id);
            try
            {
                string userId = repository.GetById(id).UserId;
                repository.Delete(id);
                repository.Save();

                ApplicationUser user = await UserManager.FindByIdAsync(userId);
                if(user != null)
                {
                    var result = await UserManager.DeleteAsync(user);
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", "Cannot delete user!");
                        AddErrors(result);
                        return View("Delete");
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                int errorCode;
                if (int.TryParse(e.Message, out errorCode) && errorCode == (int)DbError.ConstraintCheckViolation)
                {
                    ModelState.AddModelError("", "There are appointments linked to this groomer! You have to cancel related appointments in order to delete this account!");
                }
                else
                {
                    ModelState.AddModelError("", e.Message);
                }
                return View("Delete", groomer);
            }
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        private string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

    }
}

PetGroomingApplication/Controllers/PetController.cs
using Microsoft.AspNet.Identity;
using PetGroomingApplication.GenericRepository;
using PetGroomingApplication.Models;
using PetGroomingApplication.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetGroomingApplication.Controllers
{
    public class PetController : Controller
    {
        private PetRepository repository = null;
        private OwnerRepository ownerRepository = null;
        private Guid ownerID = Guid.Empty;

        public PetController()
        {
            this.repository = new PetRepository();
            this.ownerRepository = new OwnerRepository();
        }

        //public PetController(PetRepository repository)
        //{
        //    this.repository = repository;
        //}

        // GET: Pet
        [Authorize(Roles = "user")]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            ownerID = ownerRepository.GetIdByUserId(userId);
            var pets = repository.GetByOwner(ownerID);
            return View("Index", pets);
        }

        // GET: Pet/Create
        [Authorize(Roles = "user")]
        public ActionResult Create()
        {
            ViewBag.returnUrl = Request.UrlReferrer.AbsolutePath;
            return View("Create");
        }

        // POST: Pet/Create
        [HttpPost]
        [Authorize(Roles = "user")]
        public ActionResult Create(Pet pet, string returnUrl)
        {
            try
            {
                string userId = User.Identity.GetUserId();
                ownerID = ownerRepository.GetIdByUserId(userId);
                pet.OwnerID = ownerID;
                repository.Insert(pet);
                repository.Save();
                return Redirect(returnUrl);
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: Pet/Edit/5
        [Authorize(Roles = "user")]
        public ActionResult Edit(Guid id)
        {
            Pet pet = repository.GetById(id);
            return View("Edit", pet);
        }

        // POST: Pet/Edit/5
        [HttpPost]
        [Authorize(Roles = "user")]
        public ActionResult Edit(Guid id, FormCollection collection)
        {
            Pet pet = new Pet();
            try
            {
                UpdateModel(pet);
                string userId = User.Identity.GetUserId();
                ownerID = ownerRepository.GetIdByUserId(userId);
                pet.OwnerID = ownerID;
                repository.Update(pet);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit", pet);
            }
        }

        // GET: Pet/Delete/5
        [Authorize(Roles = "user")]
        public ActionResult Delete(Guid id)
        {
            Pet pet = repository.GetById(id);
            return View("Delete", pet);
        }

        // POST: Pet/Delete/5
        [HttpPost]
        [Authorize(Roles = "user")]
        public ActionResult Delete(Guid id, FormCollection collection)
        {
            try
            {
                repository.Delete(id);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                int errorCode;
                if (int.TryParse(e.Message, out errorCode) && errorCode == (int)DbError.ConstraintCheckViolation)
                {
                    ModelState.AddModelError("", "This pet have registered appointments. You have to cancel related appointments in order to delete it!");
                }
                else
                {
                    ModelState.AddModelError("", e.Message);
                }
                Pet pet = repository.GetById(id);
                return View("Delete", pet);
            }
        }
    }
}

PetGroomingApplication/Controllers/ServiceController.cs
using PetGroomingApplication.GenericRepository;
using PetGroomingApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetGroomingApplication.Controllers
{
    public class ServiceController : Controller
    {
        private IGenericRepository<Service> repository = null;

        public ServiceController()
        {
            this.repository = new GenericRepository<Service>();
        }

        public ServiceController(GenericRepository<Service> repository)
        {
            this.repository = repository;
        }
        // GET: Services
        public ActionResult Index()
        {
            var services = repository.GetAll();
            return View(services);
        }

        // GET: Services/Details/5
        public ActionResult Details(Guid id)
        {
            return View();
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Services/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Service service = new Service();
                UpdateModel(service);
                repository.Insert(service);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: Services/Edit/5
        public ActionResult Edit(Guid id)
        {
            Service service = repository.GetById(id);
            return View("Edit" , service);
        }

        // POST: Services/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, FormCollection collection)
        {
            Service service = new Service(); 
            try
            {
                string rate = collection["Rate"];
                //collection["Rate"] = decimal.Parse(rate, System.Globalization.NumberStyles.Currency);
                UpdateModel(service);
                repository.Update(service);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Services/Delete/5
        public ActionResult Delete(Guid id)
        {
            Service service = repository.GetById(id);
            return View("Delete", service);
        }

        // POST: Services/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, FormCollection collection)
        {
            try
            {
                repository.Delete(id);
                repository.Save();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                int errorCode;
                if (int.TryParse(e.Message, out errorCode) && errorCode == (int)DbError.ConstraintCheckViolation)
                {
                    ModelState.AddModelError("", "This service has registered appointments. You have to cancel related appointments in order to delete it!");
                }
                else
                {
                    ModelState.AddModelError("", e.Message);
                }
                Service service = repository.GetById(id);
                return View("Delete", service);
            }
        }
    }
}

PetGroomingApplication/Views/Shared/FriendlyErrorMessage.cshtml
@{
    ViewBag.Title = "FriendlyErrorMessage";
}

<h2>Error Message</h2>
<p>@ViewBag.errorMessage</p>

PetGroomingApplication/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        footer {
            height: 50px;
            background: PapayaWhip;
        }

        body {
            display: table;
            width: 100%;
        }

        footer {
            display: table-row;
        }
    </style>


</head>
<body>
    <div class="culmn">
        <header id="main_menu"  class="menu-scroll">
            <div class="main_menu_bg">
                <div class="container">
                    <div class="row">
                        <div class="nave_menu">
                            <nav class="navbar navbar-nav">
                                <div class="container-fluid">
                                    @Html.Partial("_LoginPartial")
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        @Html.ActionLink("Pet Grooming Salon", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                    </div>
                                    <div class="navbar-collapse collapse">
                                        <ul class="nav navbar-nav">
                                            @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@

                                            @{
                                                if (User.IsInRole("admin"))
                                                {
                                                    <li>@Html.ActionLink("Groomers", "Index", "Groomer")</li>
                                                    <li>@Html.ActionLink("Services", "Index", "Service")</li>
                                                    <li>@Html.ActionLink("Appointments", "Index", "Appointments")</li>
                                                }

                                                @{
                                                    if (User.IsInRole("staff"))
                                                    {
                                                        string calendarDate = DateTime.Today.ToString("yyyy-MM-dd");
                                                        <li>
                                                            @Html.ActionLink(
                                                                linkText: "Appointments",
                                                                actionName: "Calendar",
                                                                controllerName: "Groomer",
                                                                routeValues: new { date = calendarDate },
                                                                htmlAttributes: null
                                                            )
                                                        </li>
                                                    }
                                                }


                                                @{
                                                    if (User.IsInRole("user"))
                                                    {
                                                        <li>@Html.ActionLink("Appointment", "CreateAppointment", "Owner")</li>
                                                        <li>@Html.ActionLink("My pets", "Index", "Pet")</li>
                                                        <li>@Html.ActionLink("Edit owner profile", "Edit", "Owner")</li>

                                                    }
                                                }
                                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                            </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                      </div>

                </div>

            </div>
        </header> <!--End of header -->

        <div class="container body-content" style="margin-top:100px;">
            @RenderBody()

        </div>
 @*       <footer>
            <p>&copy; @DateTime.Now.Year -Pet Grooming Application</p>
        </footer>
*@

    </div>
                        @*@Scripts.Render("~/bundles/jquery")
                            @Scripts.Render("~/bundles/jqueryval")
                            @Scripts.Render("~/bundles/bootstrap")
                            @RenderSection("scripts", required: false)*@
</body>
</html>

PetGroomingApplication/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pet Grooming Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @RenderSection("scripts", required: false)
</head>
<body data-spy="scroll" data-target=".navbar-collapse" data-offset="70">
    <div class='preloader'><div class='loaded'>&nbsp;</div></div>
    <div class="culmn">
        <header id="main_menu" class="header navbar-fixed-top">
            <div class="main_menu_bg">
                <div class="container">
                    <div class="row">
                        <div class="nave_menu">
                            <nav class="navbar navbar-default">
                                <div class="container-fluid">
                                    
                                    @Html.Partial("_LoginPartial")

                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <a href="/Home">
                                            <img style="width:90px" src="~/Content/images/logo4.png" />
                                        </a>

                                    </div>
                                    <div class="navbar-collapse collapse navbar-left">

                                        <ul class="nav navbar-nav navbar-right">
                                            @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@

                                            <li><a href="#feature">About us</a></li>
                                            <li><a href="#service">Our services</a></li>
                                            <li><a href="#team">Our team</a></li>
                                            <li><a href="#portofolio">Photo gallery</a></li>
                                            <li><a href="#contact">Contact</a></li>
                                            <li>@Html.ActionLink("My account", "CreateAppointment", "Owner")</li>
                                        </ul>
                                    </div>
                                </div>

                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header> <!--End of header -->
        @*<div class="container body-content" >*@
        @RenderBody()

        @*</div>*@
        @*       <footer>
            <p>&copy; @DateTime.Now.Year -Pet Grooming Application</p>
        </footer>
        *@

    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap")*@



    @Scripts.Render("~/bundles/bootstrap")
 
</body>
</html>

PetGroomingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Pet Grooming Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script>
         $(function () {
             $(document).ready(function() {
                 $("#@ViewBag.targetMenu").addClass("selected");
             });
        })
    </script>
    @RenderSection("scripts", required: false)

</head>
<body data-spy="scroll" data-target=".navbar-collapse">
    <div class='preloader'><div class='loaded'>&nbsp;</div></div>
    <div class="culmn">
        <header id="main_menu" class="menu-scroll">
            <div class="main_menu_bg">
                <div class="container">
                    <div class="row">
                        <div class="nave_menu">
                            <nav class="navbar navbar-default" style="width:100%">
                                <div class="container-fluid">
                                    @Html.Partial("_LoginPartial")

                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <a href="/Home">
                                            <img style="width:90px" src="~/Content/images/logo4.png" />
                                        </a>
                                        &emsp;
                                    </div>
                                    <div class="navbar-collapse collapse">
                                        <ul class="nav navbar-nav">
                                            @if (User.IsInRole("user"))
                                            {
                                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                                <li>@Html.ActionLink("Book Appointment", "CreateAppointment", "Owner", null, new { @id = "create-appointment" })</li>
                                                <li>@Html.ActionLink("My Appointments", "Index", "Owner", null, new { @id = "appointments" })</li>
                                                <li>@Html.ActionLink("My pets", "Index", "Pet", null, new { @id = "pets" })</li>
                                                <li>@Html.ActionLink("My profile", "Edit", "Owner", null, new { @id = "my-profile" })</li>
                                            }

                                            else if (User.IsInRole("admin"))
                                            {
                                                string date = DateTime.Today.ToString("yyyy-MM-dd");
                                                <li>@Html.ActionLink("Groomers", "Index", "Groomer", null, new { @id = "groomers" })</li>
                                                <li>@Html.ActionLink("Services", "Index", "Service", null, new { @id = "services" })</li>
                                                
                                                <li>
                                                    @Html.ActionLink(
                                                        linkText: "Appointments",
                                                        actionName: "Index",
                                                        controllerName: "Appointment",
                                                        routeValues: new { date = date },
                                                        htmlAttributes: new { @id = "appointments" }
                                                    )
                                                </li>
                                            }

                                            else if (User.IsInRole("staff"))
                                            {
                                                string calendarDate = DateTime.Today.ToString("yyyy-MM-dd");
                                                <li>
                                                    @Html.ActionLink(
                                                        linkText: "Appointments",
                                                        actionName: "Calendar",
                                                        controllerName: "Groomer",
                                                        routeValues: new { date = calendarDate },
                                                        htmlAttributes: new { @id = "appointments" }
                                                    )
                                                </li>
                                                <li>
                                                    @Html.ActionLink("Statistics", "Statistics", "Groomer", null, new { @id = "groomers" })
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>

                            </nav>
                        </div>

                    </div>

                </div>

            </div>
        </header> <!--End of header -->

        <div class="container body-content" style="margin-top:100px;">
            @RenderBody()

        </div>
        @*       <footer>
                <p>&copy; @DateTime.Now.Year -Pet Grooming Application</p>
            </footer>
        *@

    </div>
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>